/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Client;
import model.PointDeVente;
import DAO.PointDeVenteDAO;
import java.util.List;

/**
 *
 * @author c.denys
 */
public class GestionPointsDeVente extends javax.swing.JFrame {

    /**
     * Creates new form accueil
     */
    private final Client client;

    public GestionPointsDeVente(Client client) {
        this.client = client;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LesPointsDeVente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 530));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Gestions des points de vente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 40, 330, 28);

        LesPointsDeVente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        LesPointsDeVente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LesPointsDeVenteItemStateChanged(evt);
            }
        });
        LesPointsDeVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LesPointsDeVenteActionPerformed(evt);
            }
        });
        getContentPane().add(LesPointsDeVente);
        LesPointsDeVente.setBounds(310, 100, 230, 22);

        jLabel2.setText("Sélectionner le point de vente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 100, 160, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InitComboBox() {
        PointDeVenteDAO pointDeVenteDAO = new PointDeVenteDAO();
        List<PointDeVente> pointsDeVente = pointDeVenteDAO.getAllPointDeVenteByIDClient(client.getIdClient());
        int nbPointsDeVente = pointsDeVente.size();
        if (!pointsDeVente.isEmpty()) {
            LesPointsDeVente.removeAllItems();
            LesPointsDeVente.addItem("Choisissez un point de vente");
            for (int i = 0; nbPointsDeVente > i; i++) {
                PointDeVente unPointDeVente;
                unPointDeVente = pointsDeVente.get(i);
                LesPointsDeVente.addItem(unPointDeVente.getNomPointDeVente() + " | ID : " + unPointDeVente.getIdPointDeVente());
            }
        }
    }

    private void LesPointsDeVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LesPointsDeVenteActionPerformed

    }//GEN-LAST:event_LesPointsDeVenteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        InitComboBox();
    }//GEN-LAST:event_formWindowOpened

    private void LesPointsDeVenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LesPointsDeVenteItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            if (LesPointsDeVente.getSelectedItem() != "Choisissez un point de vente") {
                System.out.println(LesPointsDeVente.getSelectedItem());
                String myString = (String) LesPointsDeVente.getSelectedItem();
                System.out.println(myString.charAt(myString.length() - 1));
            }
        }
    }//GEN-LAST:event_LesPointsDeVenteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPointsDeVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPointsDeVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPointsDeVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPointsDeVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Client client) {
                new GestionPointsDeVente(client).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LesPointsDeVente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
